### PR TITLE
Fail less hard on Java 11

### PR DESCRIPTION
**Pull request by dwijnand**

### CODE REVIEW

**Comment by mkurz** [comment]
What's the use of this `scalacommunitybuild` fork? Will this pull request make it into the official Play repository?

**Comment by dwijnand** [comment]
The `scalacommunitybuild` org is intended to hold forks for the general use of the community build, but they aren't intended to be long-lived forked (in theory).

I would've sent this to the play repo proper, but I didn't know how to make it work for Java 11 so I submitted it here instead.  Do you know how to map the java 11 api's into the apidocs, @mkurz?

**Comment by marcospereira** [comment]
@dwijnand sbt-api-mappings is probably the way to go here, but I'm not sure how it handles different versions of Java.

**Comment by marcospereira** [comment]
Anyway, I think that not failing for Java 9+ but also not having the links, still better than just failing.

**Comment by SethTisue** [comment]
@dwijnand at https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-jdk11-integrate-community-build/231/console I'm seeing:

```
[playframework] java.lang.NullPointerException
[playframework] 	at BuildSettings$$anonfun$playCommonSettings$17.apply(BuildSettings.scala:118)
[playframework] 	at BuildSettings$$anonfun$playCommonSettings$17.apply(BuildSettings.scala:116)
[playframework] 	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
[playframework] 	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
[playframework] 	at sbt.std.Transform$$anon$4.work(System.scala:63)
[playframework] 	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
[playframework] 	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
[playframework] 	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[playframework] 	at sbt.Execute.work(Execute.scala:237)
[playframework] 	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
[playframework] 	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
[playframework] 	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
[playframework] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
[playframework] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[playframework] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[playframework] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[playframework] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[playframework] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[playframework] 	at java.base/java.lang.Thread.run(Thread.java:834)
[playframework] [error] (Play-Exceptions/*:apiMappings) java.lang.NullPointerException
```

so there's still some problem here

**Comment by dwijnand** [comment]
Sorry about that: https://github.com/scalacommunitybuild/playframework/pull/2.

**Pull request merged**
